name: Build and push Docker image

on:
  release:
    types: [published]

jobs:
  # This workflow contains a single job called "build"
  build_and_push:
    name: Build and push the docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Install pnpm
        run: npm i -g pnpm

      # Change the version to be the correct one so the version in the image is always the correct one.
      - name: Set new version
        run: pnpm version --no-git-tag-version --allow-same-version ${{ github.event.release.tag_name }}

      # Setting up Buildx because it's needed by build-push-action
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          # Using this driver fixes the timeout issue with buildx that made it impossible to push more than one image to the GHCR.
          driver-opts: image=moby/buildkit:master
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          tags: |
            ghcr.io/nk-coding/tutor-management-system:${{ github.event.release.tag_name }}
            ghcr.io/nk-coding/tutor-management-system:latest
